/* ks/config.h - **AUTOGENERATED** kscript configuration header
 *
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, AND SHOULD NOT BE MODIFIED !!!
 *
 */

#pragma once
#ifndef KS_CONFIG_H
#define KS_CONFIG_H


#define KS_PLAT_NAME "linux"
#define KS_PLAT_SEP "/"
#define KS_PLAT_EXT_SHARED ".so"
#define KS_PLAT_EXT_STATIC ".a"
#define KS_PLAT_EXT_BINARY ""


#define KS_HAVE_MATH




#endif /* KS_CONFIG_H */
